apiVersion: v1
kind: Service
metadata:
  name: dota-service
  namespace: default
  labels:
    app: dota-service
spec:
  type: LoadBalancer
  selector:
    app: dota-service
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dota-service-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/dota-service-role
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dota-service-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - api.dota-service.example.com
    secretName: dota-service-tls
  rules:
  - host: api.dota-service.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dota-service
            port:
              number: 80
